-- =============================================================
-- LIMPIEZA: Dropear vistas writables y INSTEAD OF triggers
-- =============================================================
-- Ahora que el frontend usa .schema('iam') directamente,
-- las vistas writables en public ya NO son necesarias para el frontend.
--
-- ⚠️ IMPORTANTE: Las vistas writables TODAVÍA son necesarias para
-- las funciones SQL internas (como accept_organization_invitation,
-- handle_registered_invitation, etc.) que referencian
-- "organization_invitations" con search_path='public'.
--
-- Por ahora NO borramos las vistas. Este script es para referencia
-- futura, cuando se actualicen las funciones SQL para usar nombres
-- qualified (iam.organization_invitations).
--
-- Cuando eso esté listo, ejecutar este script:
-- =============================================================

-- ── organization_invitations ────────────────────────────────
-- DROP TRIGGER organization_invitations_insert_trigger ON public.organization_invitations;
-- DROP TRIGGER organization_invitations_update_trigger ON public.organization_invitations;
-- DROP TRIGGER organization_invitations_delete_trigger ON public.organization_invitations;
-- DROP FUNCTION IF EXISTS iam.organization_invitations_insert_fn();
-- DROP FUNCTION IF EXISTS iam.organization_invitations_update_fn();
-- DROP FUNCTION IF EXISTS iam.organization_invitations_delete_fn();
-- DROP VIEW IF EXISTS public.organization_invitations;

-- ── organization_clients ────────────────────────────────────
-- DROP TRIGGER organization_clients_insert_trigger ON public.organization_clients;
-- DROP TRIGGER organization_clients_update_trigger ON public.organization_clients;
-- DROP TRIGGER organization_clients_delete_trigger ON public.organization_clients;
-- DROP FUNCTION IF EXISTS iam.organization_clients_insert_fn();
-- DROP FUNCTION IF EXISTS iam.organization_clients_update_fn();
-- DROP FUNCTION IF EXISTS iam.organization_clients_delete_fn();
-- DROP VIEW IF EXISTS public.organization_clients;
