-- ============================================================
-- FIX: Pasar p_provider a step_send_purchase_email en los
-- 4 handle_* functions que la llaman
-- ============================================================
-- Ejecutar DESPUÉS de fix_step_send_purchase_email_provider.sql
-- ============================================================

-- ============================================================
-- 1. handle_payment_course_success
-- ============================================================
-- Buscar la línea:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'course',
--         COALESCE(v_course_name, 'Curso'),
--         p_amount,
--         p_currency,
--         v_payment_id
--     );
-- Y agregar p_provider al final:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'course',
--         COALESCE(v_course_name, 'Curso'),
--         p_amount,
--         p_currency,
--         v_payment_id,
--         p_provider          -- ← AGREGAR
--     );

-- ============================================================
-- 2. handle_payment_subscription_success
-- ============================================================
-- Buscar la línea:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'subscription',
--         COALESCE(v_plan_name, 'Plan') || ' (' || p_billing_period || ')',
--         p_amount,
--         p_currency,
--         v_payment_id
--     );
-- Y agregar p_provider al final:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'subscription',
--         COALESCE(v_plan_name, 'Plan') || ' (' || p_billing_period || ')',
--         p_amount,
--         p_currency,
--         v_payment_id,
--         p_provider          -- ← AGREGAR
--     );

-- ============================================================
-- 3. handle_upgrade_subscription_success
-- ============================================================
-- Buscar la línea:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'upgrade',
--         'Upgrade a ' || COALESCE(v_plan_name, 'Plan') || ...
--         p_amount,
--         p_currency,
--         v_payment_id
--     );
-- Y agregar p_provider al final:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'upgrade',
--         'Upgrade a ' || COALESCE(v_plan_name, 'Plan') || ...
--         p_amount,
--         p_currency,
--         v_payment_id,
--         p_provider          -- ← AGREGAR
--     );

-- ============================================================
-- 4. handle_member_seat_purchase
-- ============================================================
-- Buscar la línea:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'seat_purchase',
--         p_seats_purchased || ' asiento(s) adicional(es)',
--         p_amount,
--         p_currency,
--         v_payment_id
--     );
-- Y agregar p_provider al final:
--     PERFORM public.step_send_purchase_email(
--         p_user_id,
--         'seat_purchase',
--         p_seats_purchased || ' asiento(s) adicional(es)',
--         p_amount,
--         p_currency,
--         v_payment_id,
--         p_provider          -- ← AGREGAR
--     );

-- ============================================================
-- NOTA: Como p_provider tiene default 'mercadopago', si algún
-- caller NO se actualiza, el comportamiento es el mismo que antes
-- (backward compatible). Pero lo ideal es actualizarlos todos.
-- ============================================================
